class Datas {
  List<Map> sorular = [
    {
      "soru":
          "Fabirakatörler otomasyonu arttırmak için izin istiyor. Bu ülkenin ithalatını arttıracak ancak işsizliği arttıracak kabul ediyor musunuz?",
      "bakan": "Hazine ve Maliye Bakanı",
      "bakanImgUrl": "assets/ekonomi.jpeg",
      "cevap": null,
      "gordumu": false,
      "secenekOlumlu": "Kabul Ediyorum",
      "secenekOlumsuz": "Kabul Etmiyorum",
      "artacakDeger": "halk",
      "artacakPuan": 8,
      "azalacakDeger": "para",
      "azalacakPuan": 10,
    },
    {
      "soru":
          "Rusya bize son teknoloji s500 satmak istiyor.",
      "bakan": "Milli Savunma Bakanı",
      "bakanImgUrl": "assets/savunma.jpeg",
      "cevap": null,
      "gordumu": false,
      "secenekOlumlu": "Kabul Ediyorum",
      "secenekOlumsuz": "Kabul Etmiyorum",
      "artacakDeger": "ordu",
      "artacakPuan": 8,
      "azalacakDeger": "para",
      "azalacakPuan": 10,
    },
    {
      "soru":
          "Fabrika işçileri ağır çalışma şartlarına karşı eylem başlattı. Ağır işlerde daha düşük çalışma saati ve daha fazla tatil hakkı için kanun istiyorlar. Kabul ediyor musunuz?",
      "bakan": "İçişleri Bakanı",
      "bakanImgUrl": "assets/içişleri.jpeg",
      "cevap": null,
      "gordumu": false,
      "secenekOlumlu": "Kabul Ediyorum",
      "secenekOlumsuz": "Kabul Etmiyorum",
      "artacakDeger": "halk",
      "artacakPuan": 8,
      "azalacakDeger": "para",
      "azalacakPuan": 10,
    },
    {
      "soru":
          "Özel hastane sahipleri, devlet hastanelerinin ücretsiz sağlık hizmeti vererek vergileri çöpe attığını ve devlet hastanelerinin özelleştirilmesi gerektiğini söylüyor. Kabul ediyor musunuz?",
      "bakan": "Sağlık Bakanı",
      "bakanImgUrl": "assets/saglik.jpeg",
      "cevap": null,
      "gordumu": false,
      "secenekOlumlu": "Kabul Ediyorum",
      "secenekOlumsuz": "Kabul Etmiyorum",
      "artacakDeger": "para",
      "artacakPuan": 8,
      "azalacakDeger": "halk",
      "azalacakPuan": 10,
    },
    {
      "soru":
          "Ülkenin kuruluşunun 100. yılı şerefine devasa bir şenlik yapmak ister misiniz?",
      "bakan": "İçişleri Bakanı",
      "bakanImgUrl": "assets/içişleri.jpeg",
      "cevap": null,
      "gordumu": false,
      "secenekOlumlu": "Kabul Ediyorum",
      "secenekOlumsuz": "Kabul Etmiyorum",
      "artacakDeger": "halk",
      "artacakPuan": 8,
      "azalacakDeger": "para",
      "azalacakPuan": 10,
    },
    {
      "soru":
          "Birkaç yüksek rütbeli asker bir olup paradan ziyade halkı önemsemeniz gerektiğini söyledikleri tehdit içerikli muhtıra yayınladılar. Ne yapacaksınız?",
      "bakan": "Milli Savunma Bakanı",
      "bakanImgUrl": "assets/savunma.jpeg",
      "cevap": null,
      "gordumu": false,
      "secenekOlumlu": "Askerleri hapse tık",
      "secenekOlumsuz": "Kabullen",
      "artacakDeger": "para",
      "artacakPuan": 20,
      "azalacakDeger": "ordu",
      "azalacakPuan": 25,
    },
    {
      "soru":
          "Halk asgari ücret zammı istiyor ne yapalım ?",
      "bakan": "Hazine ve Maliye Bakanı",
      "bakanImgUrl": "assets/ekonomi.jpeg",
      "cevap": null,
      "gordumu": false,
      "secenekOlumlu": "Bunu hak ettiler zam yapalım",
      "secenekOlumsuz": "idare etsinler",
      "artacakDeger": "halk",
      "artacakPuan": 10,
      "azalacakDeger": "para",
      "azalacakPuan": 8,
    },
    {
      "soru":
          "Ordumuz için yeni teknoloji savunma sistemleri almamız gerekiyor ne yapalım ?",
      "bakan": "Milli Savunma Bakanı",
      "bakanImgUrl": "assets/savunma.jpeg",
      "cevap": null,
      "gordumu": false,
      "secenekOlumlu": "Güvenlik bizim için önemli alalım",
      "secenekOlumsuz": "Daha yeni aldık idare etsinler",
      "artacakDeger": "ordu",
      "artacakPuan": 8,
      "azalacakDeger": "para",
      "azalacakPuan": 5,
    },
    {
      "soru":
          "Fabirakatörler otomasyonu arttırmak için izin istiyor. Bu ülkenin ithalatını arttıracak ancak işsizliği arttıracak kabul ediyor musunuz?",
      "bakan": "İçişleri Bakanı",
      "bakanImgUrl": "assets/içişleri.jpeg",
      "cevap": null,
      "gordumu": false,
      "secenekOlumlu": "Kabul Ediyorum",
      "secenekOlumsuz": "Kabul Etmiyorum",
      "artacakDeger": "halk",
      "artacakPuan": 8,
      "azalacakDeger": "para",
      "azalacakPuan": 10,
    },
    {
      "soru":
          "Yurtdışından gelen teklifler var efendim. 1 fabrikamızı özelleştirebiliriz. Ne yapalım ?",
      "bakan": "Hazine ve Maliye Bakanı",
      "bakanImgUrl": "assets/ekonomi.jpeg",
      "cevap": null,
      "gordumu": false,
      "secenekOlumlu": "Para lazım özelleştirelim ",
      "secenekOlumsuz": "Paraya ihtiyacımız yok. Fabrikalar bizim için önemli",
      "artacakDeger": "para",
      "artacakPuan": 15,
      "azalacakDeger": "halk",
      "azalacakPuan": 10,
    },
  ];
}
